server:
  port: 8080
spring:
  application:
    name: spring-boot-es-demo
  elasticsearch:
    rest:
      uris: https://123.56.169.252:9200


# Elasticsearch-核心配置
# http连接超时时间
elasticsearch.connectTimeout=1000
# socket连接超时时间
elasticsearch.socketTimeout=30000
# 获取连接的超时时间
elasticsearch.connectionRequestTimeout=500
# 最大连接数
elasticsearch.maxConnTotal=100
# 最大路由连接数
elasticsearch.maxConnPerRoute=100
# 任务最长可执行时间 (单位:小时)
elasticsearch.executeTimeout=8
# 用户名
elasticsearch.username=admin
# 密码
elasticsearch.password=123456
